Repository guillaumearm/SPT_The_Escape, pull requests merged in 2024-08, with the labels that each got.

#28 Update bossConfig.json
  user/mods/SWAG/config/bossConfig.json
Labels: Tweak

#26 Update RaidOverhaul config.json
  user/mods/RaidOverhaul/config/config.json
Labels: Tweak

#38 fix: some lootingbots config changes
  BepInEx/config/me.skwizzy.lootingbots.cfg
Labels: Tweak

#37 docs(README): update some mods
  README.md
  user/mods/Trap-CustomQuests/package.json
Labels: documentation

#49 feat: add AllTheClothes mod
  README.md
  user/mods/rairaitheraichu-alltheclothes-2.0.1/config/config.jsonc
  user/mods/rairaitheraichu-alltheclothes-2.0.1/package.json
Labels: feature
